const cards=document.querySelector('#cards'),detail=document.querySelector('#detail'),search=document.querySelector('#search'),rank=document.querySelector('#rank');
const labels={all:'全部资料',artifact:'法宝',herb:'灵植',ore:'灵矿',weapon:'兵刃与装备',entity:'敌对生物',biome:'群系',dimension:'世界与维度',block:'功能方块'};
let category='all',selected='';
const asset=e=>`../src/main/resources/assets/abyssredemptiondaomod/${e.icon}`;
function visible(){const q=search.value.trim().toLowerCase();return WIKI_DATA.filter(e=>(category==='all'||e.category===category)&&(!rank.value||e.rank===rank.value)&&(!q||`${e.name} ${e.en||''} ${e.id} ${e.lore||''}`.toLowerCase().includes(q)))}
function render(){const list=visible();document.querySelector('#section-title').textContent=labels[category];document.querySelector('#count').textContent=`共 ${list.length} 条资料`;cards.innerHTML=list.map(e=>`<button class="card ${selected===e.id?'active':''}" data-id="${e.id}"><img src="${asset(e)}" alt=""><span><b>${e.name}</b><small>${e.rankName||labels[e.category]}</small></span></button>`).join('')||'<p>没有匹配资料</p>';cards.querySelectorAll('.card').forEach(b=>b.onclick=()=>show(b.dataset.id))}
function show(id){selected=id;const e=WIKI_DATA.find(x=>x.id===id),facts=(e.facts||[]).map(([k,v])=>`<div><span>${k}</span><b>${v}</b></div>`).join('');detail.innerHTML=`<img class="detail-icon" src="${asset(e)}" alt="${e.name}"><h2>${e.name}</h2><div class="en">${e.en||e.id}</div><div><span class="badge">${labels[e.category]}</span>${e.rankName?`<span class="badge">${e.rankName}</span>`:''}</div><p>${e.lore||'道途劫灭模组资料。'}</p><div class="meta"><div><span>资料 ID</span><b>${e.id}</b></div>${facts||`<div><span>最大堆叠</span><b>${e.stack||64}</b></div>`}<div><span>${e.category==='dimension'?'进入方式':'获取方式'}</span><b>${e.obtain||'世界探索 / 战利品'}</b></div></div>${['artifact','weapon'].includes(e.category)?`<div class="command">/give @p abyssredemptiondaomod:${e.id}</div>`:''}`;render()}
function categories(){const counts=Object.keys(labels).map(k=>[k,k==='all'?WIKI_DATA.length:WIKI_DATA.filter(e=>e.category===k).length]).filter(x=>x[1]);document.querySelector('#categories').innerHTML=counts.map(([k,n])=>`<button class="category ${k===category?'active':''}" data-cat="${k}">${labels[k]} <span>${n}</span></button>`).join('');document.querySelectorAll('.category').forEach(b=>b.onclick=()=>{category=b.dataset.cat;selected='';categories();render()})}
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden'));document.querySelector(`#${b.dataset.view}`).classList.remove('hidden')});
search.oninput=render;rank.onchange=render;categories();render();
