from pathlib import Path
import json
import re


ROOT = Path(__file__).resolve().parents[1]
DOC = ROOT / "describe/设定集.md"
LANG = ROOT / "src/main/resources/assets/abyssredemptiondaomod/lang"
ITEMS = ROOT / "src/main/java/com/abyssredemption/daomod/registry/ModItems.java"


def compact(text):
    return re.sub(r"\s+", "", text).replace("\\.", ".")


def setting_entries(lines):
    entries = {}
    for index, line in enumerate(lines):
        artifact = re.match(r"^\d+\\?\.\s+(.+)$", line)
        resource = re.match(r"^\d+\\?\.\s+([^：]+)：(.+)$", line)
        if 285 <= index <= 760 and artifact:
            name = artifact.group(1).replace("名：", "·")
            details = []
            for follow in lines[index + 1:index + 9]:
                follow = compact(follow)
                if follow.startswith(("功能：", "法则：", "简介：")):
                    details.append(follow.split("：", 1)[1])
            if details:
                entries[name] = details[-1]
        elif 770 <= index <= 895 and resource:
            entries[resource.group(1)] = compact(resource.group(2))
    return entries


def main():
    lines = DOC.read_text(encoding="utf-8").splitlines()
    lore_by_name = setting_entries(lines)
    source = ITEMS.read_text(encoding="utf-8")
    ids = re.findall(r'new CodexEntry\("([^"]+)"', source)
    zh_path = LANG / "zh_cn.json"
    en_path = LANG / "en_us.json"
    zh = json.loads(zh_path.read_text(encoding="utf-8-sig"))
    en = json.loads(en_path.read_text(encoding="utf-8-sig"))
    zh.update({
        "gui.daomod.sect": "道统：%s",
        "gui.daomod.sect0": "散修",
        "gui.daomod.sect1": "太上天枢剑宗",
        "gui.daomod.sect2": "造化仙宗",
        "gui.daomod.sect3": "大雷音寺",
        "gui.daomod.sect4": "罗刹魔教",
        "command.daomod.sect.already_joined": "你已有道统，无法自行改投他宗。",
        "command.daomod.sect.joined": "你已拜入%s。",
        "message.daomod.stage_breakthrough": "气机圆满，突破至第%s重。",
        "message.daomod.major_breakthrough": "天地共鸣，你已踏入%s境！",
        "message.daomod.tribulation": "天劫降临：需承受%s道劫雷。",
        "message.daomod.heart_demon": "业力反噬，心魔劫因%s点因果而生。",
        "entity.abyssredemptiondaomod.sword_attendant": "天枢剑侍",
        "entity.abyssredemptiondaomod.creation_disciple": "造化器徒",
        "entity.abyssredemptiondaomod.thunder_monk": "雷音武僧",
        "entity.abyssredemptiondaomod.rakshasa_cultist": "罗刹魔徒",
        "item.abyssredemptiondaomod.sword_attendant_spawn_egg": "天枢剑侍生成蛋",
        "item.abyssredemptiondaomod.creation_disciple_spawn_egg": "造化器徒生成蛋",
        "item.abyssredemptiondaomod.thunder_monk_spawn_egg": "雷音武僧生成蛋",
        "item.abyssredemptiondaomod.rakshasa_cultist_spawn_egg": "罗刹魔徒生成蛋",
        "entity.abyssredemptiondaomod.xuanyuan": "轩辕·始源剑祖",
        "entity.abyssredemptiondaomod.dugu_qiubai": "独孤求败·破理剑客",
        "entity.abyssredemptiondaomod.qinglian_jianxian": "青莲剑仙",
        "entity.abyssredemptiondaomod.ye_gucheng": "叶孤城·守路人",
        "entity.abyssredemptiondaomod.shen_duzhou": "沈独舟·孤星剑首",
        "item.abyssredemptiondaomod.xuanyuan_spawn_egg": "轩辕生成蛋",
        "item.abyssredemptiondaomod.dugu_qiubai_spawn_egg": "独孤求败生成蛋",
        "item.abyssredemptiondaomod.qinglian_jianxian_spawn_egg": "青莲剑仙生成蛋",
        "item.abyssredemptiondaomod.ye_gucheng_spawn_egg": "叶孤城生成蛋",
        "item.abyssredemptiondaomod.shen_duzhou_spawn_egg": "沈独舟生成蛋",
        "entity.abyssredemptiondaomod.nameless_artificer": "无名匠师·兵甲之父",
        "entity.abyssredemptiondaomod.gongshu_ban": "公输班·傀儡神匠",
        "entity.abyssredemptiondaomod.ge_hong": "葛洪·丹道圣手",
        "entity.abyssredemptiondaomod.ouye_zi": "欧冶子·铸魂师",
        "entity.abyssredemptiondaomod.su_hongyi": "苏红衣·算尽天机",
        "item.abyssredemptiondaomod.nameless_artificer_spawn_egg": "无名匠师生成蛋",
        "item.abyssredemptiondaomod.gongshu_ban_spawn_egg": "公输班生成蛋",
        "item.abyssredemptiondaomod.ge_hong_spawn_egg": "葛洪生成蛋",
        "item.abyssredemptiondaomod.ouye_zi_spawn_egg": "欧冶子生成蛋",
        "item.abyssredemptiondaomod.su_hongyi_spawn_egg": "苏红衣生成蛋",
        "entity.abyssredemptiondaomod.ming_wang": "冥王·幽冥司主",
        "entity.abyssredemptiondaomod.dizang": "地藏·镇狱者",
        "entity.abyssredemptiondaomod.damo": "达摩·禅宗祖师",
        "entity.abyssredemptiondaomod.blood_river_ancestor": "血河老祖·魔道枭雄",
        "entity.abyssredemptiondaomod.wuhua": "无花·血菩提",
        "item.abyssredemptiondaomod.ming_wang_spawn_egg": "冥王生成蛋",
        "item.abyssredemptiondaomod.dizang_spawn_egg": "地藏生成蛋",
        "item.abyssredemptiondaomod.damo_spawn_egg": "达摩生成蛋",
        "item.abyssredemptiondaomod.blood_river_ancestor_spawn_egg": "血河老祖生成蛋",
        "item.abyssredemptiondaomod.wuhua_spawn_egg": "无花生成蛋",
        "entity.abyssredemptiondaomod.mo_xuan": "墨玄·虚空掘墓人",
        "entity.abyssredemptiondaomod.guanghan_fairy": "广寒仙子·逐月者",
        "entity.abyssredemptiondaomod.fengshen_daoist": "封神道人·秩序之锁",
        "entity.abyssredemptiondaomod.grave_keeper": "守墓人·纪元观察者",
        "entity.abyssredemptiondaomod.ning_fan": "宁凡·逆命野修",
        "item.abyssredemptiondaomod.mo_xuan_spawn_egg": "墨玄生成蛋",
        "item.abyssredemptiondaomod.guanghan_fairy_spawn_egg": "广寒仙子生成蛋",
        "item.abyssredemptiondaomod.fengshen_daoist_spawn_egg": "封神道人生成蛋",
        "item.abyssredemptiondaomod.grave_keeper_spawn_egg": "守墓人生成蛋",
        "item.abyssredemptiondaomod.ning_fan_spawn_egg": "宁凡生成蛋",
        "entity.abyssredemptiondaomod.kuafu": "夸父·逐日巨神",
        "entity.abyssredemptiondaomod.jingwei": "精卫·填海志",
        "entity.abyssredemptiondaomod.houyi": "后羿·陨星者",
        "entity.abyssredemptiondaomod.xingtian": "刑天·战神残躯",
        "entity.abyssredemptiondaomod.xuanyuan_fourteen": "轩辕十四·最后的巨人",
        "item.abyssredemptiondaomod.kuafu_spawn_egg": "夸父生成蛋",
        "item.abyssredemptiondaomod.jingwei_spawn_egg": "精卫生成蛋",
        "item.abyssredemptiondaomod.houyi_spawn_egg": "后羿生成蛋",
        "item.abyssredemptiondaomod.xingtian_spawn_egg": "刑天生成蛋",
        "item.abyssredemptiondaomod.xuanyuan_fourteen_spawn_egg": "轩辕十四生成蛋",
        "item.abyssredemptiondaomod.sword_legends_challenge": "剑道纪元战帖",
        "item.abyssredemptiondaomod.creation_masters_challenge": "造化纪元战帖",
        "item.abyssredemptiondaomod.buddha_demon_challenge": "佛魔纪元战帖",
        "item.abyssredemptiondaomod.forbidden_ones_challenge": "禁忌纪元战帖",
        "item.abyssredemptiondaomod.ancient_bloodline_challenge": "荒古纪元战帖",
        "tooltip.abyssredemptiondaomod.challenge_group0": "挑战：剑道领袖",
        "tooltip.abyssredemptiondaomod.challenge_group1": "挑战：造化宗师",
        "tooltip.abyssredemptiondaomod.challenge_group2": "挑战：佛魔两极",
        "tooltip.abyssredemptiondaomod.challenge_group3": "挑战：禁忌存在",
        "tooltip.abyssredemptiondaomod.challenge_group4": "挑战：荒古遗脉",
        "tooltip.abyssredemptiondaomod.challenge_required": "最低境界：%s",
        "message.abyssredemptiondaomod.challenge_realm_low": "境界不足，至少达到%s方可下帖。",
        "message.abyssredemptiondaomod.challenge_begins": "%s应战而来！附近修士可共同迎敌。",
        "message.abyssredemptiondaomod.challenge_already_active": "附近已有传奇强者应战，无法再次下帖。",
        "message.abyssredemptiondaomod.legendary_shared_reward": "你参与击败传奇强者，修炼进度 +%s。",
        "message.abyssredemptiondaomod.challenge_previous_required": "尚未完成前一纪元的传奇挑战。",
        "advancements.abyssredemptiondaomod.legend_group_0.title": "一锋定乾坤",
        "advancements.abyssredemptiondaomod.legend_group_0.description": "参与击败一位剑道领袖",
        "advancements.abyssredemptiondaomod.legend_group_1.title": "万物皆可炼",
        "advancements.abyssredemptiondaomod.legend_group_1.description": "参与击败一位造化宗师",
        "advancements.abyssredemptiondaomod.legend_group_2.title": "慈悲与狂乱",
        "advancements.abyssredemptiondaomod.legend_group_2.description": "参与击败一位佛魔强者",
        "advancements.abyssredemptiondaomod.legend_group_3.title": "逆命与真相",
        "advancements.abyssredemptiondaomod.legend_group_3.description": "参与击败一位禁忌存在",
        "advancements.abyssredemptiondaomod.legend_group_4.title": "血脉的余晖",
        "advancements.abyssredemptiondaomod.legend_group_4.description": "参与击败一位荒古遗脉",
        "message.abyssredemptiondaomod.bishui_xichanzhu": "禅珠泛起清光，水火暂不能侵。",
        "message.abyssredemptiondaomod.zhiyuan_feixingnu": "飞星离弦，流火命中目标。",
        "message.abyssredemptiondaomod.naying_ping": "影气覆身，你的身形隐入暗处。",
        "message.abyssredemptiondaomod.ganshan_bian": "赶山之力震退了 %s 个目标。",
        "message.abyssredemptiondaomod.cangjing_ye": "叶脉经文流转，心神愈发清明。",
        "message.abyssredemptiondaomod.jieling_suo": "截灵锁封住了目标的灵力流转。",
        "message.abyssredemptiondaomod.zhaodan_jing": "镜光照见了 %s 道生灵气息。",
        "message.abyssredemptiondaomod.no_target": "前方没有可锁定的目标。",
        "message.abyssredemptiondaomod.shanhe_cuo": "微型山岳轰然落下，镇住目标。",
        "message.abyssredemptiondaomod.lihuo_fentian_ling": "离火缠身，地火开始灼烧目标。",
        "message.abyssredemptiondaomod.fuyu_fanyun_gai": "云盖遮天，灵雨应召而至。",
        "message.abyssredemptiondaomod.fulong_jinsuo": "金索循气而出，目标体形越大束缚越重。",
        "message.abyssredemptiondaomod.chuanxiao_suo": "穿霄梭化作流光，护你破空而行。",
        "message.abyssredemptiondaomod.zhenmo_yin": "镇魔梵音震伤了 %s 个目标。",
        "message.abyssredemptiondaomod.juling_wanqi_zhen": "万旗展开，为 %s 名修士聚成临时灵地。",
        "message.abyssredemptiondaomod.yinyang_hint": "潜行右键翻至生面；对目标使用则显死面。",
        "message.abyssredemptiondaomod.yinyang_life": "两界碑白面朝前，生机回流。",
        "message.abyssredemptiondaomod.yinyang_death": "两界碑黑面朝前，削去目标生机。",
        "message.abyssredemptiondaomod.wending_laoxiu": "老朽轻叩炉壁，副手装备被重新锻合。",
        "message.abyssredemptiondaomod.fentian_zhulong": "烛龙睁目，寂灭火域吞没了 %s 个目标。",
        "message.abyssredemptiondaomod.jiushi_cihang": "慈航愿力护持了 %s 名修士。",
        "message.abyssredemptiondaomod.zhaohun_qianmian": "千面齐哭，%s 个目标坠入污秽幻境。",
        "message.abyssredemptiondaomod.duntian_wuxing": "无形蝶翼轻振，你的气息从天地间隐去。",
        "message.abyssredemptiondaomod.xiangmo_numu": "怒目金刚一击震碎目标身上的法则加持。",
        "message.abyssredemptiondaomod.nongchao_yiyin": "遗音引动虚空潮汐，将目标放逐出去。",
        "message.abyssredemptiondaomod.lietian_bengshan": "崩山携星辰重压轰落。",
        "message.abyssredemptiondaomod.suanjin_shensuan": "神算洞察了 %s 个目标的功法破绽。",
        "message.abyssredemptiondaomod.wuxing_dingshi_ta": "定世塔接管五行，压制了 %s 个目标。",
        "message.abyssredemptiondaomod.suihan_kurong_zhong": "钟声冻结一瞬纪元，凝滞了 %s 个目标。",
        "message.abyssredemptiondaomod.zhutian_xingxiu_tu": "星宿易位，目标被流放至远方。",
        "message.abyssredemptiondaomod.hunyuan_qiankun_san": "乾坤伞逆转攻守，因果回护己身。",
        "message.abyssredemptiondaomod.fantian_fudi_yin": "重力骤变，%s 个目标被镇向大地。",
        "message.abyssredemptiondaomod.qibao_qingjing_shu": "七宝神光刷落了 %s 个目标的法力加持。",
        "message.abyssredemptiondaomod.yinyang_chongsu_lu": "阴阳炉火重塑肉身，生机复归圆满。",
        "message.abyssredemptiondaomod.miedu_honghulu": "真名既出，灭度法力必中目标。",
        "message.abyssredemptiondaomod.guixu_dinghai_zhu": "定海柱镇住一切混乱，你的状态归于稳定。",
        "message.abyssredemptiondaomod.suiyue_liuzhuan_lun": "岁月逆流，%s 个目标的时间近乎停滞。",
        "message.abyssredemptiondaomod.wanfa_benyuan_shengjuan": "圣卷展开，万法本源加持己身。",
        "message.abyssredemptiondaomod.lunhui_pan": "轮回盘转动，为 %s 名修士重塑状态。",
        "message.abyssredemptiondaomod.geshi_zhimen": "隔世之门洞开，你已抵达%s。",
        "dimension.abyssredemptiondaomod.chenhuan_realm": "尘寰界",
        "dimension.abyssredemptiondaomod.diluo_abyss": "帝落渊",
        "dimension.abyssredemptiondaomod.eternal_immortal_realm": "永恒仙域",
        "message.abyssredemptiondaomod.hundun_zhenjie_zhong": "混沌钟声震伤并掀飞了 %s 个目标。",
        "message.abyssredemptiondaomod.zhongsheng_yinguo_jitan": "你献祭自身生机，引爆了 %s 个目标的因果。",
        "message.abyssredemptiondaomod.xukong_dingxing_mao": "定星锚锁住虚空，牵制了 %s 个目标。",
        "message.abyssredemptiondaomod.tiandao_caijue_chui": "裁决既下，天雷应声而落。",
        "message.abyssredemptiondaomod.hongmeng_chuangshi_lian": "创世莲绽放，为 %s 名修士重燃生机。",
        "message.abyssredemptiondaomod.consume_herb": "服下%s，药性开始在经脉中流转。",
        "tooltip.abyssredemptiondaomod.required_realm": "最低驾驭境界：%s",
        "message.abyssredemptiondaomod.realm_too_low": "神魂无法承载此物，至少需要达到%s。",
        "tooltip.abyssredemptiondaomod.qi_cost": "催动消耗：%s 炁",
        "message.abyssredemptiondaomod.qi_too_low": "炁不足，催动此物需要 %s 炁。",
    })
    en.update({
        "gui.daomod.sect": "Sect: %s",
        "gui.daomod.sect0": "Unaffiliated Cultivator",
        "gui.daomod.sect1": "Supreme Tianshu Sword Sect",
        "gui.daomod.sect2": "Creation Immortal Sect",
        "gui.daomod.sect3": "Great Thunder Monastery",
        "gui.daomod.sect4": "Rakshasa Demon Cult",
        "command.daomod.sect.already_joined": "You already follow a sect and cannot switch freely.",
        "command.daomod.sect.joined": "You have joined %s.",
        "message.daomod.stage_breakthrough": "Your qi completes a cycle. You reach stage %s.",
        "message.daomod.major_breakthrough": "Heaven and earth resonate. You enter %s!",
        "message.daomod.tribulation": "Tribulation descends: endure %s bolts of heavenly lightning.",
        "message.daomod.heart_demon": "Your %s karma manifests as a heart-demon tribulation.",
        "entity.abyssredemptiondaomod.sword_attendant": "Tianshu Sword Attendant",
        "entity.abyssredemptiondaomod.creation_disciple": "Creation Sect Disciple",
        "entity.abyssredemptiondaomod.thunder_monk": "Thunder Monastery Monk",
        "entity.abyssredemptiondaomod.rakshasa_cultist": "Rakshasa Cultist",
        "item.abyssredemptiondaomod.sword_attendant_spawn_egg": "Tianshu Sword Attendant Spawn Egg",
        "item.abyssredemptiondaomod.creation_disciple_spawn_egg": "Creation Disciple Spawn Egg",
        "item.abyssredemptiondaomod.thunder_monk_spawn_egg": "Thunder Monk Spawn Egg",
        "item.abyssredemptiondaomod.rakshasa_cultist_spawn_egg": "Rakshasa Cultist Spawn Egg",
        "entity.abyssredemptiondaomod.xuanyuan": "Xuanyuan, First Sword Ancestor",
        "entity.abyssredemptiondaomod.dugu_qiubai": "Dugu Qiubai, Logic-Breaking Swordsman",
        "entity.abyssredemptiondaomod.qinglian_jianxian": "Azure Lotus Sword Immortal",
        "entity.abyssredemptiondaomod.ye_gucheng": "Ye Gucheng, Keeper of the Path",
        "entity.abyssredemptiondaomod.shen_duzhou": "Shen Duzhou, Lone Star Sword Master",
        "item.abyssredemptiondaomod.xuanyuan_spawn_egg": "Xuanyuan Spawn Egg",
        "item.abyssredemptiondaomod.dugu_qiubai_spawn_egg": "Dugu Qiubai Spawn Egg",
        "item.abyssredemptiondaomod.qinglian_jianxian_spawn_egg": "Azure Lotus Sword Immortal Spawn Egg",
        "item.abyssredemptiondaomod.ye_gucheng_spawn_egg": "Ye Gucheng Spawn Egg",
        "item.abyssredemptiondaomod.shen_duzhou_spawn_egg": "Shen Duzhou Spawn Egg",
        "entity.abyssredemptiondaomod.nameless_artificer": "Nameless Artificer, Father of Arms",
        "entity.abyssredemptiondaomod.gongshu_ban": "Gongshu Ban, Divine Puppet Smith",
        "entity.abyssredemptiondaomod.ge_hong": "Ge Hong, Alchemy Sage",
        "entity.abyssredemptiondaomod.ouye_zi": "Ouye Zi, Soul Forger",
        "entity.abyssredemptiondaomod.su_hongyi": "Su Hongyi, Heavenly Strategist",
        "item.abyssredemptiondaomod.nameless_artificer_spawn_egg": "Nameless Artificer Spawn Egg",
        "item.abyssredemptiondaomod.gongshu_ban_spawn_egg": "Gongshu Ban Spawn Egg",
        "item.abyssredemptiondaomod.ge_hong_spawn_egg": "Ge Hong Spawn Egg",
        "item.abyssredemptiondaomod.ouye_zi_spawn_egg": "Ouye Zi Spawn Egg",
        "item.abyssredemptiondaomod.su_hongyi_spawn_egg": "Su Hongyi Spawn Egg",
        "entity.abyssredemptiondaomod.ming_wang": "King of the Underworld",
        "entity.abyssredemptiondaomod.dizang": "Dizang, Warden of the Abyss",
        "entity.abyssredemptiondaomod.damo": "Damo, Patriarch of Chan",
        "entity.abyssredemptiondaomod.blood_river_ancestor": "Blood River Ancestor",
        "entity.abyssredemptiondaomod.wuhua": "Wuhua, Blood Bodhi",
        "item.abyssredemptiondaomod.ming_wang_spawn_egg": "Underworld King Spawn Egg",
        "item.abyssredemptiondaomod.dizang_spawn_egg": "Dizang Spawn Egg",
        "item.abyssredemptiondaomod.damo_spawn_egg": "Damo Spawn Egg",
        "item.abyssredemptiondaomod.blood_river_ancestor_spawn_egg": "Blood River Ancestor Spawn Egg",
        "item.abyssredemptiondaomod.wuhua_spawn_egg": "Wuhua Spawn Egg",
        "entity.abyssredemptiondaomod.mo_xuan": "Mo Xuan, Void Gravedigger",
        "entity.abyssredemptiondaomod.guanghan_fairy": "Guanghan Fairy, Moon Chaser",
        "entity.abyssredemptiondaomod.fengshen_daoist": "Fengshen Daoist, Lock of Order",
        "entity.abyssredemptiondaomod.grave_keeper": "Grave Keeper, Epoch Observer",
        "entity.abyssredemptiondaomod.ning_fan": "Ning Fan, Fate-Defying Wanderer",
        "item.abyssredemptiondaomod.mo_xuan_spawn_egg": "Mo Xuan Spawn Egg",
        "item.abyssredemptiondaomod.guanghan_fairy_spawn_egg": "Guanghan Fairy Spawn Egg",
        "item.abyssredemptiondaomod.fengshen_daoist_spawn_egg": "Fengshen Daoist Spawn Egg",
        "item.abyssredemptiondaomod.grave_keeper_spawn_egg": "Grave Keeper Spawn Egg",
        "item.abyssredemptiondaomod.ning_fan_spawn_egg": "Ning Fan Spawn Egg",
        "entity.abyssredemptiondaomod.kuafu": "Kuafu, Sun-Chasing Giant",
        "entity.abyssredemptiondaomod.jingwei": "Jingwei, Will of the Sea",
        "entity.abyssredemptiondaomod.houyi": "Houyi, Star-Felling Archer",
        "entity.abyssredemptiondaomod.xingtian": "Xingtian, Undying War God",
        "entity.abyssredemptiondaomod.xuanyuan_fourteen": "Xuanyuan Fourteen, Last Giant",
        "item.abyssredemptiondaomod.kuafu_spawn_egg": "Kuafu Spawn Egg",
        "item.abyssredemptiondaomod.jingwei_spawn_egg": "Jingwei Spawn Egg",
        "item.abyssredemptiondaomod.houyi_spawn_egg": "Houyi Spawn Egg",
        "item.abyssredemptiondaomod.xingtian_spawn_egg": "Xingtian Spawn Egg",
        "item.abyssredemptiondaomod.xuanyuan_fourteen_spawn_egg": "Xuanyuan Fourteen Spawn Egg",
        "item.abyssredemptiondaomod.sword_legends_challenge": "Sword Epoch Challenge",
        "item.abyssredemptiondaomod.creation_masters_challenge": "Creation Epoch Challenge",
        "item.abyssredemptiondaomod.buddha_demon_challenge": "Buddha-Demon Epoch Challenge",
        "item.abyssredemptiondaomod.forbidden_ones_challenge": "Forbidden Epoch Challenge",
        "item.abyssredemptiondaomod.ancient_bloodline_challenge": "Ancient Bloodline Challenge",
        "tooltip.abyssredemptiondaomod.challenge_group0": "Challenge: Sword Leaders",
        "tooltip.abyssredemptiondaomod.challenge_group1": "Challenge: Creation Masters",
        "tooltip.abyssredemptiondaomod.challenge_group2": "Challenge: Buddha and Demon",
        "tooltip.abyssredemptiondaomod.challenge_group3": "Challenge: Forbidden Ones",
        "tooltip.abyssredemptiondaomod.challenge_group4": "Challenge: Ancient Bloodlines",
        "tooltip.abyssredemptiondaomod.challenge_required": "Required realm: %s",
        "message.abyssredemptiondaomod.challenge_realm_low": "You must reach %s before issuing this challenge.",
        "message.abyssredemptiondaomod.challenge_begins": "%s answers the challenge. Nearby cultivators may join the battle.",
        "message.abyssredemptiondaomod.challenge_already_active": "A legendary challenger is already active nearby.",
        "message.abyssredemptiondaomod.legendary_shared_reward": "You helped defeat a legend. Cultivation progress +%s.",
        "message.abyssredemptiondaomod.challenge_previous_required": "Complete the previous epoch challenge first.",
        "advancements.abyssredemptiondaomod.legend_group_0.title": "One Edge Rules All",
        "advancements.abyssredemptiondaomod.legend_group_0.description": "Help defeat a sword leader",
        "advancements.abyssredemptiondaomod.legend_group_1.title": "All Things May Be Forged",
        "advancements.abyssredemptiondaomod.legend_group_1.description": "Help defeat a creation master",
        "advancements.abyssredemptiondaomod.legend_group_2.title": "Mercy and Madness",
        "advancements.abyssredemptiondaomod.legend_group_2.description": "Help defeat a Buddha-Demon legend",
        "advancements.abyssredemptiondaomod.legend_group_3.title": "Fate and Truth",
        "advancements.abyssredemptiondaomod.legend_group_3.description": "Help defeat a forbidden one",
        "advancements.abyssredemptiondaomod.legend_group_4.title": "Echoes of Ancient Blood",
        "advancements.abyssredemptiondaomod.legend_group_4.description": "Help defeat an ancient bloodline legend",
        "message.abyssredemptiondaomod.bishui_xichanzhu": "The prayer bead wards away water and flame.",
        "message.abyssredemptiondaomod.zhiyuan_feixingnu": "The meteor bolt strikes its target.",
        "message.abyssredemptiondaomod.naying_ping": "Shadow essence conceals your form.",
        "message.abyssredemptiondaomod.ganshan_bian": "The mountain-driving force repelled %s targets.",
        "message.abyssredemptiondaomod.cangjing_ye": "The scripture leaf clears your mind.",
        "message.abyssredemptiondaomod.jieling_suo": "The lock seals the target's spiritual flow.",
        "message.abyssredemptiondaomod.zhaodan_jing": "The mirror revealed %s living auras.",
        "message.abyssredemptiondaomod.no_target": "There is no target ahead.",
        "message.abyssredemptiondaomod.shanhe_cuo": "A miniature mountain crashes down upon the target.",
        "message.abyssredemptiondaomod.lihuo_fentian_ling": "Undying earthfire coils around the target.",
        "message.abyssredemptiondaomod.fuyu_fanyun_gai": "The canopy calls down a spiritual rain.",
        "message.abyssredemptiondaomod.fulong_jinsuo": "The golden rope binds larger targets more tightly.",
        "message.abyssredemptiondaomod.chuanxiao_suo": "The shuttle carries you through the sky in a warded streak.",
        "message.abyssredemptiondaomod.zhenmo_yin": "The demon-quelling tone struck %s targets.",
        "message.abyssredemptiondaomod.juling_wanqi_zhen": "The banners raised a spirit field for %s cultivators.",
        "message.abyssredemptiondaomod.yinyang_hint": "Sneak-use for life; use on a target for death.",
        "message.abyssredemptiondaomod.yinyang_life": "The white face restores your vitality.",
        "message.abyssredemptiondaomod.yinyang_death": "The black face strips away the target's vitality.",
        "message.abyssredemptiondaomod.wending_laoxiu": "The elder reforges the damaged item in your off hand.",
        "message.abyssredemptiondaomod.fentian_zhulong": "Zhulong's annihilating domain consumed %s targets.",
        "message.abyssredemptiondaomod.jiushi_cihang": "Cihang's vows protected %s cultivators.",
        "message.abyssredemptiondaomod.zhaohun_qianmian": "A thousand faces dragged %s targets into torment.",
        "message.abyssredemptiondaomod.duntian_wuxing": "The formless spirit hides your presence from heaven.",
        "message.abyssredemptiondaomod.xiangmo_numu": "The wrathful spirit shattered the target's enchantments.",
        "message.abyssredemptiondaomod.nongchao_yiyin": "A void tide banished the target.",
        "message.abyssredemptiondaomod.lietian_bengshan": "The weight of a star crashes down.",
        "message.abyssredemptiondaomod.suanjin_shensuan": "Divine calculus exposed %s targets' weaknesses.",
        "message.abyssredemptiondaomod.wuxing_dingshi_ta": "The tower seized the five elements from %s targets.",
        "message.abyssredemptiondaomod.suihan_kurong_zhong": "The bell froze an epoch around %s targets.",
        "message.abyssredemptiondaomod.zhutian_xingxiu_tu": "The stars shifted and exiled the target.",
        "message.abyssredemptiondaomod.hunyuan_qiankun_san": "The umbrella reversed causality to guard its bearer.",
        "message.abyssredemptiondaomod.fantian_fudi_yin": "Altered gravity crushed %s targets toward the earth.",
        "message.abyssredemptiondaomod.qibao_qingjing_shu": "Purifying light stripped the power from %s targets.",
        "message.abyssredemptiondaomod.yinyang_chongsu_lu": "The furnace reshaped your body and restored its life.",
        "message.abyssredemptiondaomod.miedu_honghulu": "The invoked true name made the spell unavoidable.",
        "message.abyssredemptiondaomod.guixu_dinghai_zhu": "The sea pillar stabilized all chaos around you.",
        "message.abyssredemptiondaomod.suiyue_liuzhuan_lun": "Time reversed and nearly stopped for %s targets.",
        "message.abyssredemptiondaomod.wanfa_benyuan_shengjuan": "The origin scripture blessed you with all arts.",
        "message.abyssredemptiondaomod.lunhui_pan": "The reincarnation disc restored %s cultivators.",
        "message.abyssredemptiondaomod.geshi_zhimen": "The gate opens. You arrive in %s.",
        "dimension.abyssredemptiondaomod.chenhuan_realm": "Mortal Dust Realm",
        "dimension.abyssredemptiondaomod.diluo_abyss": "Emperorfall Abyss",
        "dimension.abyssredemptiondaomod.eternal_immortal_realm": "Eternal Immortal Realm",
        "message.abyssredemptiondaomod.hundun_zhenjie_zhong": "The chaos bell struck and hurled %s targets.",
        "message.abyssredemptiondaomod.zhongsheng_yinguo_jitan": "You sacrificed vitality to ignite the karma of %s targets.",
        "message.abyssredemptiondaomod.xukong_dingxing_mao": "The void anchor bound %s targets in space.",
        "message.abyssredemptiondaomod.tiandao_caijue_chui": "Heaven answered the judgment with lightning.",
        "message.abyssredemptiondaomod.hongmeng_chuangshi_lian": "The creation lotus restored %s cultivators.",
        "message.abyssredemptiondaomod.consume_herb": "You consume %s and its essence enters your meridians.",
        "tooltip.abyssredemptiondaomod.required_realm": "Required realm: %s",
        "message.abyssredemptiondaomod.realm_too_low": "Your soul cannot bear this item. Required realm: %s.",
        "tooltip.abyssredemptiondaomod.qi_cost": "Qi cost: %s",
        "message.abyssredemptiondaomod.qi_too_low": "Insufficient qi. This item requires %s qi.",
    })

    missing = []
    for item_id in ids:
        key = f"item.abyssredemptiondaomod.{item_id}"
        name = zh[key]
        lore = lore_by_name.get(name)
        if lore is None:
            missing.append(name)
            continue
        zh[f"{key}.lore"] = lore
        en[f"{key}.lore"] = "An item recorded in the Dao Codex."

    if missing:
        raise RuntimeError("Missing lore: " + ", ".join(missing))
    zh_path.write_text(json.dumps(zh, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    en_path.write_text(json.dumps(en, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Synchronized lore for {len(ids)} items")


if __name__ == "__main__":
    main()
